## numpy와 닮은 파이토치 (pytorch)

In [1]:
import torch
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=torch.tensor([1,2, 3.1   , 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [2]:
a = torch.tensor([1,2,3,4,5])
print(a.shape)
print(a.ndim)
print(a.numel())

torch.Size([5])
1
5


In [3]:
A = torch.tensor([ [1,2,3], [3,4,5] ]) # 이 셀부터는 import torch 는 실행 했다 치고 작성
# A = torch.tensor([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim)  # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [4]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [5]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c)

tensor([5, 7, 9])


In [6]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C) 
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [7]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


## pytorch 의 인덱싱 슬라이스

In [8]:
a=torch.tensor([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([ [1,2,3], [4,5,6], [7,8,9] ])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [10]:
# 3차원 행렬 인덱싱
A=torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,   
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(A[0,1,2])
print(A.ndim)

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
3
torch.Size([1, 1, 4])


In [11]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[ [True,True,False,False] ])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [12]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[ torch.tensor([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [13]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,True], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## pytorch의 여러 함수들

In [14]:
A=torch.randn(3,3) # Normal 의 n
B=torch.rand(3,3) # 이건 uniform
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

tensor([[-0.3976, -2.1101,  0.6973],
        [ 1.3968, -0.8406,  0.7623],
        [-0.4831,  0.5613,  0.1137]])
tensor([[0.8480, 0.7713, 0.5792],
        [0.4500, 0.6499, 0.0243],
        [0.6407, 0.0426, 0.8098]])
tensor([[-0.3976, -2.1101,  0.6973],
        [-0.4831,  0.5613,  0.1137]])


In [15]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 1.0829,  1.1503,  1.5825],
        [ 0.8859,  0.0736, -0.6155],
        [-0.2030,  0.6725, -0.9619]])
tensor([[1.0829, 1.1503, 1.5825],
        [0.8859, 0.0736, 0.6155],
        [0.2030, 0.6725, 0.9619]])
tensor([[1.0406, 1.0725, 1.2580],
        [0.9412, 0.2712, 0.7845],
        [0.4505, 0.8201, 0.9808]])
tensor([[2.9534, 3.1593, 4.8671],
        [2.4251, 1.0764, 0.5404],
        [0.8163, 1.9592, 0.3822]])
tensor([[ 0.0797,  0.1401,  0.4590],
        [-0.1212, -2.6094, -0.4853],
        [-1.5948, -0.3967, -0.0388]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[ 1.,  1.,  2.],
        [ 1.,  0., -1.],
        [-0.,  1., -1.]])
tensor([[ 1.0800,  1.1500,  1.5800],
        [ 0.8900,  0.0700, -0.6200],
        [-0.2000,  0.6700, -0.9600]])
tensor([[ 1.,  1.,  1.],
        [ 0.,  0., -1.],
        [-1.,  0., -1.]])
tensor([[2., 2., 2.],
        [1., 1., -0.],
        [-0., 1., -0.]])


In [16]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float임 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [17]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [18]:
A=torch.randn(3,4)
print(A)
# print(torch.max(A))
# print(torch.max(A,dim=0))
print(torch.max(A,dim=1))
# print(torch.max(A,dim=0, keepdims=True))
print(torch.max(A,dim=1, keepdims=True)) # 3 행 1열 짜리 2D tensor
# print(torch.min(A))
# print(torch.min(A,dim=0))
# print(torch.min(A,dim=1))
# print(torch.argmax(A))
# print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
# print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[-1.9289, -2.4406,  0.4843, -0.2238],
        [ 1.0686, -1.4250, -0.5246,  2.0686],
        [-1.1450,  0.2210,  1.2743,  0.1781]])
torch.return_types.max(
values=tensor([0.4843, 2.0686, 1.2743]),
indices=tensor([2, 3, 2]))
torch.return_types.max(
values=tensor([[0.4843],
        [2.0686],
        [1.2743]]),
indices=tensor([[2],
        [3],
        [2]]))


In [19]:
a=torch.randn(6,1)
# print(a)
# a_sorted=torch.sort(a,dim=0)
# print(a_sorted)

# a=torch.randn(6,1)
# print(a)
# print(a.sort(dim=0))
# print(a.sort(dim=0, descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor(1.0904)
tensor(1.0904)
tensor([[0.6309],
        [1.0904],
        [1.3789],
        [0.5114],
        [0.2214],
        [0.8886]])
tensor([[0.6309],
        [1.0904],
        [1.3789],
        [0.5114],
        [0.2214],
        [0.8886]])


In [20]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[ 0.7480,  0.5358,  0.4362, -2.4694],
        [ 2.0630, -1.0652, -0.2977, -0.4488],
        [ 1.7199, -0.6084,  0.5276, -0.1979]])
tensor(0.9432)
tensor([-0.7494,  0.2514,  1.4412])
tensor([[-0.7494],
        [ 0.2514],
        [ 1.4412]])
tensor(0.0786)
tensor([-0.1873,  0.0628,  0.3603])
tensor([[-0.1873],
        [ 0.0628],
        [ 0.3603]])
tensor(1.2205)
tensor([[-0.7494],
        [ 0.2514],
        [ 1.4412]])
tensor([[-0.1873],
        [ 0.0628],
        [ 0.3603]])
tensor(1.2205)


In [21]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

tensor([3, 4, 4, 1, 2, 4, 3, 3, 2, 3, 1, 2])
torch.Size([12])
tensor([[[3, 4, 4],
         [1, 2, 4]],

        [[3, 3, 2],
         [3, 1, 2]]])
3


In [22]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b)
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose 는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [23]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [24]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape) 
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [25]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

C=torch.vstack([A,B])
D=torch.hstack([A,B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다.

E=torch.cat([A,B], dim=0)
F=torch.cat([A,B], dim=1)
G=torch.cat([A,B], dim=2)

print(C)
print(D)
print(E)
print(F)
print(G)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([

In [26]:
A = torch.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [27]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [28]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
C=torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [29]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone()
B[0,0]=100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @ 에 대해 좀만 더

In [30]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [31]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

C=A@B.repeat(32,1,1)
D=A@B

print(C.shape)
print(D.shape)
print((C-D).abs().max())

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor(9.5367e-07)


In [32]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)
print(A)
print(A_repeat)
print(A_repeat.shape)

tensor([[0.2648, 0.8609, 0.1311],
        [0.2895, 0.0844, 0.2622]])
tensor([[[[0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.0844, 0.2622, 0.2895, 0.0844, 0.2622],
          [0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.0844, 0.2622, 0.2895, 0.0844, 0.2622],
          [0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.0844, 0.2622, 0.2895, 0.0844, 0.2622]]],


        [[[0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.0844, 0.2622, 0.2895, 0.0844, 0.2622],
          [0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.0844, 0.2622, 0.2895, 0.0844, 0.2622],
          [0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.0844, 0.2622, 0.2895, 0.0844, 0.2622]]],


        [[[0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.0844, 0.2622, 0.2895, 0.0844, 0.2622],
          [0.2648, 0.8609, 0.1311, 0.2648, 0.8609, 0.1311],
          [0.2895, 0.08

## numpy <-> torch 왔다갔다 가능

In [33]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])
A=torch.tensor(a) # A=torch.from_numpy(a)
B=b.numpy() # B=np.array(b)
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


## 딥러닝을 가능케한 autograd

In [34]:
x=torch.tensor([1.], requires_grad=True) # float 이여야해서 1.
print(x)

tensor([1.], requires_grad=True)


In [35]:
x=torch.tensor([1.])
print(x)
print(x.requires_grad)

x.requires_grad=True
print(x)
print(x.requires_grad)

tensor([1.])
False
tensor([1.], requires_grad=True)
True


In [36]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y) # PowBackward0 가 붙어있다!

print(x.grad)
y.backward()
print(x.grad) # y=x**2을 미분한 2x의 x 값에 1을 대입한 gradient 값

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [37]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y)
# y.retain_grad() # 이걸 하면 y.grad도 볼 수 있다

z=3*y
print(z) # MulBackward0 가 붙어있다!

z.backward()
print(x.grad) # chain rule로 알아냄
# print(y.grad) # warning! 중간건 안된다

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])


In [38]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
z=3*y

y.backward() # 이렇게하면 y에서부터 뒤로 넘어감 (backward!)
print(x.grad)

tensor([2.])


In [39]:
x=torch.tensor([1.], requires_grad=True)
a=x**2
b=a+1
print(b) # AddBackward0 가 붙어있다!
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [40]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [41]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= y*x**2
z.backward()
print(x.grad)
print(y.grad)

tensor([2.])
tensor([1.])


In [42]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
y=torch.sum(x**2) # x1**2 + x2**2 + x3**2
y.backward()

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [43]:
x=torch.tensor([1.] ,requires_grad=True)
x.requires_grad=False
# tranfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

tensor([1.])


In [44]:
x=torch.tensor([2.] ,requires_grad=True)
x=x.detach() # detach도 많이 쓰이는 듯
print(x)
y=x**2
print(y)

tensor([2.])
tensor([4.])


In [45]:
# detach 와 torch.no_grad
x=torch.tensor([1.], requires_grad=True)
# chain rule을 위해 계속 grad_fu을 update 하니까 grad_fn 잠시 안 계산하고 싶을 때 torch.no_grad
# 모델 테스트 시에는 불필요하게 메모리 쓸 필요 없기 때문!
with torch.no_grad():
    y=x**2
    print(x.requires_grad)
    print(y)
print(x.requires_grad)
# y.backward() # error!
y=x**2
print(y)

x=torch.tensor([1.], requires_grad=True)
x=x.detach()
y = x**2
print(x.requires_grad)
print(y)
# y.backward() # error!

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)
False
tensor([1.])


In [46]:
# !pip install torchviz
# from torchviz import make_dot
x=torch.tensor([1., 2.],requires_grad=True)
# make_dot(x)
# make_dot(x**2)
# make_dot(x**2+1)
make_dot((x**2+1)**2)

NameError: name 'make_dot' is not defined

## 간단한 인공신경망 만들기

In [4]:
import torch
from torch import nn

x = torch.tensor([1.])
model = nn.Linear(1, 1) # 입력 node 한 개, 출력 node 한 개인 layer 만들기

print(model.weight)
print(model.bias)

fc1 = nn.Linear(1, 3)
fc2 = nn.Linear(3, 1)

print('1' , fc1.weight)
print('1', fc1.bias)

print('2', fc2.weight)
print('2', fc2.bias)

Parameter containing:
tensor([[-0.9534]], requires_grad=True)
Parameter containing:
tensor([-0.6698], requires_grad=True)
1 Parameter containing:
tensor([[ 0.3641],
        [-0.8798],
        [ 0.2725]], requires_grad=True)
1 Parameter containing:
tensor([-0.1013,  0.3389,  0.2886], requires_grad=True)
2 Parameter containing:
tensor([[-0.3414,  0.4921, -0.4435]], requires_grad=True)
2 Parameter containing:
tensor([0.3223], requires_grad=True)


In [47]:
import torch
from torch import nn

x=torch.tensor([1.])
model = nn.Linear(1,1) # 입력 node 한 개, 출력 node 한 개인 layer 만듦

print(model.weight) # 만들면서 initialize 함
print(model.bias)

y = model(x)
print(y)

y = x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[-0.8642]], requires_grad=True)
Parameter containing:
tensor([-0.9483], requires_grad=True)
tensor([-1.8125], grad_fn=<AddBackward0>)
tensor([-1.8125], grad_fn=<AddBackward0>)


In [ ]:
fc1 = nn.Linear(1,3) # fully-connected
fc2 = nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

x=torch.tensor([1.])
y = (x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias
# nn.Linear 는 개x채x행x열에서 "채" 형태로 (1D data) 들어오길 기대하는 녀석이다.
# 즉, 노드 하나가 곧 한 채널의 의미한다.
# 따라서, 데이터 여러개를 통과시키고 싶다면 개x채 의 형태로 줘야 함
# why T? weight도 개x채 형태로 만들기 위함!
# 일단, weight shape 개x채에서 채는 무조건 앞에 거 채널 개수와 맞추셈!
# 예를 들어, nn.Linear(2,3) 이면 앞에거 채널 개수는 2 따라서 ?x2 인데
# 두 채널 값을 가지고 3개의 노드를 만드는 거라서 3x2 가 된다!

print(y)
# input size: 1
# fc1.weight.T size: 1x3
# fc1.bias size: 3
# fc2.weight.T size: 3x1
# fc2.bias size: 1

Parameter containing:
tensor([[0.7723],
        [0.8549],
        [0.9242]], requires_grad=True)
Parameter containing:
tensor([ 0.7878, -0.9535, -0.4586], requires_grad=True)
Parameter containing:
tensor([[-0.3404, -0.2877,  0.3690]], requires_grad=True)
Parameter containing:
tensor([-0.1028], requires_grad=True)
tensor([ 1.5601, -0.0986,  0.4656], grad_fn=<AddBackward0>)
tensor([-0.4337], grad_fn=<AddBackward0>)
tensor([-0.4337], grad_fn=<AddBackward0>)


In [ ]:
fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

model = nn.Sequential(fc1, fc2) # layer 풀칠
x=torch.tensor([1.])
print(model(x))

tensor([ 0.1443,  1.7302, -0.6704], grad_fn=<AddBackward0>)
tensor([-0.8868], grad_fn=<AddBackward0>)
tensor([-0.8868], grad_fn=<AddBackward0>)


In [ ]:
model = nn.Sequential(nn.Linear(2,5), # 여기는 채,채
                      nn.Linear(5,10),
                      nn.Linear(10,3))

x=torch.randn(2)
print(x)
print(model(x))

x=torch.randn(1,2)
print(x)
print(model(x))

x=torch.randn(5,2) # 개x채 => 두 개의 채널 값(키, 몸무게)을 가지는 데이터(사람) 5개를 통과시킴
print(x)
print(model(x))

x=torch.randn(2,3,1,4,5,2)
print(model(x).shape)

tensor([-0.2115, -1.6457])
tensor([0.5339, 0.5663, 0.4219], grad_fn=<AddBackward0>)
tensor([[1.1064, 0.4146]])
tensor([[-0.1059, -0.0736,  0.6442]], grad_fn=<AddmmBackward0>)
tensor([[ 0.7434, -0.2427],
        [-0.4870, -0.8473],
        [ 0.4725,  0.1137],
        [-1.1611, -0.3709],
        [-0.5012, -1.5173]])
tensor([[0.0809, 0.1192, 0.5892],
        [0.5228, 0.4744, 0.2909],
        [0.1205, 0.1075, 0.4898],
        [0.6698, 0.5209, 0.0719],
        [0.6060, 0.6002, 0.3330]], grad_fn=<AddmmBackward0>)
torch.Size([2, 3, 1, 4, 5, 3])


In [6]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.fc1 = nn.Linear(2, 5)
        self.fc2 = nn.Linear(5, 10)
        self.fc3 = nn.Linear(10, 3)
        
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.sig1(x)
        
        x = self.fc2(x)
        x = self.sig2(x)
        
        x = self.fc3(x)
        x = self.sig3(x)        
        return x
    
model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

tensor([[0.5012, 0.5274, 0.4322],
        [0.5040, 0.5292, 0.4290],
        [0.5038, 0.5285, 0.4314],
        [0.4948, 0.5270, 0.4262],
        [0.5001, 0.5262, 0.4369]], grad_fn=<SigmoidBackward0>)


In [7]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(2,5)
        self.fc2 = nn.Linear(5,10)
        self.fc3 = nn.Linear(10,3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.sig1(x)
        x = self.fc2(x)
        x = self.sig2(x)
        x = self.fc3(x)
        x = self.sig3(x)
        return x

model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

print(model)

tensor([[0.7183, 0.5138, 0.5413],
        [0.7189, 0.5168, 0.5416],
        [0.7182, 0.5137, 0.5417],
        [0.7173, 0.5091, 0.5409],
        [0.7175, 0.5111, 0.5431]], grad_fn=<SigmoidBackward0>)
MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)


In [14]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(2,5)
        self.fc2 = nn.Linear(5,10)
        self.fc3 = nn.Linear(10,3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()

        self.linear = nn.Sequential(self.fc1, self.sig1, self.fc2, self.sig2, self.fc3, self.sig3)

    def forward(self, x):
        x = self.linear(x)
        return x
    
model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)

print(model)

tensor([[0.4448, 0.5583, 0.5691],
        [0.4443, 0.5596, 0.5707],
        [0.4448, 0.5596, 0.5687],
        [0.4432, 0.5706, 0.5665],
        [0.4440, 0.5678, 0.5653]], grad_fn=<SigmoidBackward0>)
MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)


In [15]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4218,  0.6093],
         [ 0.4592, -0.5893],
         [-0.0871,  0.1680],
         [-0.5685,  0.0893],
         [-0.6980,  0.1494]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1339, -0.6308,  0.2007, -0.6867, -0.4656], requires_grad=True),
 Parameter containing:
 tensor([[ 0.3040,  0.1403,  0.2546,  0.3048, -0.0540],
         [ 0.2061, -0.2994, -0.3473, -0.2330,  0.4443],
         [-0.2467,  0.0047, -0.2847, -0.3106, -0.0751],
         [-0.2370, -0.2876, -0.2107,  0.0273, -0.0462],
         [ 0.3033, -0.0088,  0.2316, -0.0278, -0.2794],
         [-0.1726, -0.0897, -0.3795,  0.2602,  0.3932],
         [-0.1954, -0.3824, -0.2151,  0.1923,  0.4264],
         [-0.0387, -0.3015, -0.1206,  0.3032,  0.3487],
         [-0.4204,  0.3652, -0.2802, -0.1673,  0.1967],
         [-0.1810,  0.3644,  0.1516,  0.0798, -0.3035]], requires_grad=True),
 Parameter containing:
 tensor([-0.2927,  0.3361, -0.1953, -0.2058, -0.3700,  0.0729,  0.2255, -0.0234,
  

In [10]:
print(model)
print(model.fc1.weight)
print(model.fc2.bias)

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)
Parameter containing:
tensor([[ 0.6296, -0.3819],
        [-0.0243, -0.2920],
        [ 0.0700, -0.4534],
        [-0.0839,  0.1845],
        [-0.1553,  0.1148]], requires_grad=True)
Parameter containing:
tensor([ 0.2208, -0.3960, -0.1305, -0.3380,  0.2226, -0.3816,  0.3645,  0.0415,
         0.2662, -0.2441], requires_grad=True)


In [16]:
class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Sequential(
            nn.Linear(2,5),
            nn.Sigmoid(),
            nn.Linear(5,10),
            nn.Sigmoid(),
            nn.Linear(10,3),
            nn.Sigmoid())
        
    def forward(self,x):
        x = self.linear(x)
        return x

model2 = MyModel2()
x = torch.randn(5,2)
y = model2(x)
print(y)

tensor([[0.6899, 0.4923, 0.5152],
        [0.6932, 0.4950, 0.5105],
        [0.6937, 0.4910, 0.5113],
        [0.6892, 0.4963, 0.5147],
        [0.6903, 0.4930, 0.5145]], grad_fn=<SigmoidBackward0>)


In [17]:
print(model2)

MyModel2(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)


In [ ]:
print(model2)
print(model2.linear[0].weight)
print(model2.linear[-2].bias)

MyModel2(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Parameter containing:
tensor([[ 0.5882, -0.1803],
        [-0.3234,  0.6736],
        [ 0.1816, -0.3730],
        [-0.5313,  0.1610],
        [-0.2035, -0.4490]], requires_grad=True)
Parameter containing:
tensor([-0.2463, -0.3069, -0.2348], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1498, -0.1774],
         [-0.1540,  0.5480],
         [ 0.3895,  0.4730],
         [-0.0553,  0.5704],
         [-0.4322, -0.5768]], requires_grad=True), Parameter containing:
 tensor([ 0.5022, -0.5783,  0.3279, -0.1828, -0.2740], requires_grad=True), Parameter containing:
 tensor([[-1.9592e-04, -3.1074e-01,  9.8688e-02,  1.2608e-02, -4.2887e-01],
         [-3.2016e-02, -3.8420e-01,  1.4005e-01, -3.2193e-02,  1.2688e-01],
         [ 1.2562e-01,  8.4013e-02, -1.1773e-01, -8.5302e-02, -4.4347e-01],
         [-2.7976e-01, -2.8719e-02,  2.8292e-01,  4.1799e-02,  2.8570e-04],
         [ 4.2156e-02, -2.9544e-01,  3.6284e-01,  3.5578e-01,  1.2462e-01],
         [ 3.2279e-01, -3.6989e-01,  2.4944e-01, -1.2068e-01,  1.9016e-01],
         [-3.7973e-02, -3.1601e-01, -1.2153e-01, -4.4226e-01, -2.3349e-01],
         [ 3.4167e-01, -1.0767e-01, -2.7544e-01,  2.1396e-01,  2.2648e-01],
         [ 5.5263e-02, -3.7972e-02, -2.7386e-01,  2.4645e-01, -2.9669e-01],
      

In [ ]:
# 파라미터 수 구하기
num = sum([p.numel() for p in model.parameters() if p.requires_grad])
print(num)

108


## weight initialization

In [ ]:
# 내 필기용 : He initialization 이 공식 문서랑 다르다? => paper에 맞게 구현됐고 torch 공식 문서만 틀림
import torch
from torch import nn

Fin=5000
Fout=1000
w = torch.zeros(141, Fin)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu') # forward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fin)))
w = torch.zeros(Fout, 212)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu') # backward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fout)))

# CNN?
N=32
C=64
H=6
W=10
w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(C*H*W))))

w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(N*H*W))))